REASON = 'REASON'
PURPOSE = 'PURPOSE'
CLIENT = 'CLIENT'
FIO = 'FIO'
NCERTIFICATE = 'NCERTIFICATE'
TELEPHONE = 'TELEPHONE'
ADDRESS = 'ADDRESS'
EMAIL  ='EMAIL'
ORGANIZATION = 'ORGANIZATION'
MP_DATA = 'DATA'

TITLE_KEY = ['REASON','PURPOSE','CLIENT','FIO','NCERTIFICATE','TELEPHONE','ADDRESS','EMAIL','ORGANIZATION','DATA']
INPUT_DATA_KEY = ['NAME', 'NOTE']